name = "Inertia"
uuid = "58d22092-de16-4bdf-bc5b-1f5634c2cdd0"
authors = ["tom <tomrottier@hotmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "1"
julia = "1"
